### ISSUE TITLE
Pruebas sustentacion 13/02

### ISSUE THREAD

**Issue by diegocar** [Santiago-Rocha/Proyecto-poob#9]
Poner esquina como clase, representar la esquina diferente, en forma de L, tener cuidado con las esquinas izq y der es decir que tengan una orientacion y sea posible generar el bloque.

arreglar fold para cuando un bloque esta contenido en otro y verificar que no deje agregar un mismo punto mas de una vez({150,150}

**Comment by Santiago-Rocha** [comment]
Si yo le paso las esquinas cambiadas(i.e Top = {100,100}, Bottom = {60,50} ) que deberia pasar?

**Comment by diegocar** [comment]
no
